package clasesHibernate;
// Generated 16 feb 2024 10:46:20 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Capitales generated by hbm2java
 */
public class Capitales implements java.io.Serializable {

	private Integer codCapital;
	private String nombre;
	private Set poblacioneses = new HashSet(0);

	public Capitales() {
	}

	public Capitales(String nombre, Set poblacioneses) {
		this.nombre = nombre;
		this.poblacioneses = poblacioneses;
	}

	public Integer getCodCapital() {
		return this.codCapital;
	}

	public void setCodCapital(Integer codCapital) {
		this.codCapital = codCapital;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPoblacioneses() {
		return this.poblacioneses;
	}

	public void setPoblacioneses(Set poblacioneses) {
		this.poblacioneses = poblacioneses;
	}

}
