package clasesHibernate;
// Generated 16 feb 2024 10:46:20 by Hibernate Tools 6.3.1.Final

/**
 * Poblaciones generated by hbm2java
 */
public class Poblaciones implements java.io.Serializable {

	private Integer codPoblacion;
	private Capitales capitales;
	private String nombre;
	private Integer habitantes;

	public Poblaciones() {
	}

	public Poblaciones(Capitales capitales, String nombre, Integer habitantes) {
		this.capitales = capitales;
		this.nombre = nombre;
		this.habitantes = habitantes;
	}

	public Integer getCodPoblacion() {
		return this.codPoblacion;
	}

	public void setCodPoblacion(Integer codPoblacion) {
		this.codPoblacion = codPoblacion;
	}

	public Capitales getCapitales() {
		return this.capitales;
	}

	public void setCapitales(Capitales capitales) {
		this.capitales = capitales;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getHabitantes() {
		return this.habitantes;
	}

	public void setHabitantes(Integer habitantes) {
		this.habitantes = habitantes;
	}

}
